### ISSUE TITLE
Switch to RFC5245Bis

### ISSUE THREAD

**Issue by backkem** [gortc/ice#2]
According to the  [Transports for WebRTC](https://tools.ietf.org/html/draft-ietf-rtcweb-transports) spec it seems we should be implementing [RFC5245Bis](https://tools.ietf.org/html/draft-ietf-ice-rfc5245bis) instead of [RFC5245](https://tools.ietf.org/html/rfc5245). Should we switch over to that spec?

**Comment by ernado** [comment]
Thank you for investigation, we definitely need to switch to RFC5245Bis
